site_name: COCONUT[KG] Docs
site_url: http://coconut-kg.aksw.org/
extra:
  homepage: http://coconut-kg.aksw.org/
nav:
    - About: index.md
    - Extraction process: extraction/index.md
    - Dataset statistics: dataset/index.md
    - SPARQL querying: query/index.md
    - Improving: improve/index.md

theme:
  icon:
    logo: material/arrow-left
  name: material
  palette:
    primary: green
    accent: green
